container:
  image: google/dart

task:
  pub_cache:
    folder: $HOME/.pub-cache
    fingerprint_script: sha256sum pubspec.yaml
    populate_script: pub get

  resolve_dependencies_script: pub get

  matrix:
    - name: Linux Test
      container:
        image: google/dart

      env:
        CODECOV_TOKEN: ENCRYPTED[83b9647d08b6f8864b8af2b476ac7814f695d9bd9f11e37da8b2d75eb93986e0cb7fce8fcdaec6739ee7652458e84445]

      test_script: pub run test
      coverage_script: bash tool/coverage.sh
