name: redis
version: 0.1.0

environment:
  sdk: '>=2.3.0 < 3.0.0'

dependencies:
  structlog:
    path: '/home/roman/Development/vanesyan/structlog'

dev_dependencies:
  meta: '^1.1.6'
  test: '^1.5.3'
